### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by dani0105** [dani0105/word-count#2]
All languages have words that you don't want to count like in Spanish with "La,el,los,nos, etc...". It is necessary to find a good way to ignore those words and that can be adapted to other languages (not just create a var that stores those words as it is now)

**Comment by ObaidAshraf** [comment]
There are many NLP libraries supported in Python such as NLTK, Spacy, Gensim, sklean etc. These libraries contains built-in list of "stop words" (for different languages). These lists are also usually updated on new release. I think it can be used to serve the purpose. 

What are you thoughts?

**Comment by dani0105** [comment]
I was reading about it and I think it can work.
