### ISSUE TITLE
Support more text files 

### ISSUE THREAD

**Issue by dani0105** [dani0105/word-count#4]
At the moment it is only possible to load pdf files, so I want to expand the supported text files.

**Comment by 2brownc** [comment]
What files formats do you plan to support?

**Comment by dani0105** [comment]
I was thinking of `txt`, `doc` and `docx`. Those are the most common extensions, I think.

**Comment by 2brownc** [comment]
I see, ok. Can I work on this?

**Comment by 2brownc** [comment]
Is Python 3.10 supported? If so I can use `match` instead of `if-elif` when ascertaining file format. So what do you think?

Edit: I have used `match`.
